# inspired by Leandro Lima https://github.com/leoisl/grp_meeting/blob/main/.github/workflows/ci.yaml
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, MacOS-latest, Windows-latest ]
        python-version: [ 3.9, "3.10", 3.11 ]
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install .
    
    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.0

    - name: Run pre-commit CI
      uses: pre-commit/action@v3.0.0
      if: always()

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      
    - name: Install CI
      run:  make install-ci

    - name: Test
      run:  make test
