# inspired by Leandro Lima https://github.com/leoisl/grp_meeting/blob/main/.github/workflows/release-please.yaml
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: amira
          changelog-types: >
            [
              { "type": "build", "section": "Build System", "hidden": false },
              { "type": "ci", "section": "Continuous Integration", "hidden": false },
              { "type": "chore", "section": "Miscellaneous Chores", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false },
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "perf", "section": "Performance Improvements", "hidden": false },
              { "type": "refactor", "section": "Code Refactoring", "hidden": false },
              { "type": "style", "section": "Styles", "hidden": false },
              { "type": "test", "section": "Tests", "hidden": false }
            ]
          token: ${{ secrets.RELEASEPLEASEPAT }}

      - name: Install Singularity
      env:
        SINGULARITY_VERSION: 3.5.3
        GOPATH: /tmp/go
      run: |
        mkdir -p $GOPATH
        sudo mkdir -p /usr/local/var/singularity/mnt
        mkdir -p $GOPATH/src/github.com/sylabs
        cd $GOPATH/src/github.com/sylabs
        wget https://github.com/hpcng/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
        tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
        cd singularity
        ./mconfig -v -p /usr/local
        make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
        sudo make -C ./builddir install

    - name: Build Singularity container
      env:
        SINGULARITY_RECIPE: Singularity.def
        OUTPUT_CONTAINER: amira_${{env.RELEASE_VERSION}}.sif
      run: |
        ls
        if [ -f "${SINGULARITY_RECIPE}" ]; then
            sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
        else
            echo "${SINGULARITY_RECIPE} is not found."
            echo "Present working directory: $PWD"
            ls
        fi