# inspired by https://github.com/iqbal-lab-org/viridian/blob/master/.github/workflows/build.yaml
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: singularity build
jobs:
  singularity-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Singularity
        env:
          SINGULARITY_VERSION: 3.5.3
          GOPATH: /tmp/go
        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt
          mkdir -p $GOPATH/src/github.com/sylabs
          cd $GOPATH/src/github.com/sylabs
          wget https://github.com/hpcng/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
          tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
          cd singularity
          ./mconfig -v -p /usr/local
          make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
          sudo make -C ./builddir install

      - name: Build Singularity container
        env:
          SINGULARITY_RECIPE: Singularity.def
          OUTPUT_CONTAINER: amira_${{env.RELEASE_VERSION}}.img
        run: |
          ls
          if [ -f "${SINGULARITY_RECIPE}" ]; then
              sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
          else
              echo "${SINGULARITY_RECIPE} is not found."
              echo "Present working directory: $PWD"
              ls
          fi